---
# title: "Key Knowledge and Skills"
# author: "Ashley Holliday"
# output: html_document
---
---
title: "Welcome"
---


Thank you for visiting my site. Here you will find my professional portfolio. Included are my resume, a brief section of an interview, and a few pesonal projects demonstrating the scope of my work.

Key Knowledge and Skills

RStudio Proficiency - data filtering and manipulation, basic web design, data analysis and visualization
Excel Proficiency - project and budget analysis, loan amortization



I have learned to be adaptable in a high-pressure environment, working to stay within time constraints when sudden changes arise. Through this, I am confident in my ability to learn to experience, and develop newly acquired skills without loss of efficiency. 

Through my education, I have a strong foundation in statistics based code writing, using RStudio. Through this I am able to provide visualizations of statistical data analysis - a key component in risk analysis and finance-based decisions I’ve extended my utilization of code writing into other areas including graphic design and website construction*. I feel that being able to continue to grow with the use of new technologies in a role in keeping up with the demands of such a dynamic economy.



*This site was created through the use of RStudio and GitHub. 

